-- 계정생성
CREATE USER ZINUS IDENTIFIED BY 1234;
-- 권한부여
GRANT ALL PRIVILEGES TO ZINUS;

-- 테이블 삭제
DROP TABLE "MEMBER";
DROP TABLE FAQ;
DROP TABLE MAGAZINE;
DROP TABLE NOTICE_FILE;
DROP TABLE NOTICE;
DROP TABLE CATALOG_FILE;
DROP TABLE "CATALOG";
DROP TABLE QNA_FILE;
DROP TABLE QNA;
DROP TABLE ITEM_REIVEW_FILE;
DROP TABLE ITEM_REIVEW;
DROP TABLE ITEM_IMAGE;
DROP TABLE ITEM;


-- 테이블 생성
CREATE TABLE "MEMBER" (
    ID          VARCHAR2(30)    PRIMARY KEY,
    PASS        VARCHAR2(50)    NOT NULL,
    NAME        VARCHAR2(30)    NOT NULL,
    EMAIL       VARCHAR2(100)   NOT NULL,
    PHONE       VARCHAR2(20)    NOT NULL,
    TEL         VARCHAR2(30),
    ZIPCODE     VARCHAR2(10)    NOT NULL,
    ADDRESS     VARCHAR2(200)   NOT NULL,
    ADDR_DETAIL VARCHAR2(200)   NOT NULL,
    GENDER      VARCHAR2(10)    NOT NULL,
    BIRTH       VARCHAR2(20),
    ISADMIN     VARCHAR2(10)
);

CREATE TABLE ITEM (
    NO          NUMBER          PRIMARY KEY,
    NAME        VARCHAR2(200)   NOT NULL,
    TYPE        VARCHAR2(50)    NOT NULL,
    TEXT        VARCHAR2(500)   NOT NULL,
    PRICE       NUMBER          NOT   NULL,
    POINT       VARCHAR2(50)    NOT NULL,
    REGDATE     DATE            DEFAULT SYSDATE,
    SIZENAME    VARCHAR2(100)   NOT NULL,
    POSTER      VARCHAR2(200)   NOT NULL
);

CREATE  TABLE ITEM_IMAGE (
    NO          NUMBER          PRIMARY KEY,
    NAME        VARCHAR2(200)   NOT NULL,
    ITEMNO      NUMBER          REFERENCES ITEM(NO)
);

CREATE TABLE ITEM_REIVEW (
    NO          NUMBER          PRIMARY KEY,
    TITLE       VARCHAR2(200)   NOT NULL,
    WRITER      VARCHAR2(50)    NOT NULL,
    REGDATE     DATE            DEFAULT SYSDATE,
    CONTENT     CLOB,
    RATING      NUMBER          DEFAULT 0
);

CREATE TABLE ITEM_REIVEW_FILE (
    NO          NUMBER          PRIMARY KEY,
    OFILE       VARCHAR2(300)   NOT NULL,
    NFILE       VARCHAR2(300)   NOT NULL,
    REGDATE     DATE            DEFAULT SYSDATE,
    REVIEWNO    NUMBER          REFERENCES ITEM_REIVEW(NO)
);

CREATE TABLE QNA (
    NO          NUMBER          PRIMARY KEY,
    CATE        VARCHAR2(100)   NOT NULL,
    WRITER      VARCHAR2(30)    NOT NULL,
    PASS        VARCHAR2(50),
    TITLE       VARCHAR2(200)   NOT NULL,
    CONTENT     CLOB,
    REGDATE     DATE            DEFAULT SYSDATE,
    ITEMNO      NUMBER          REFERENCES ITEM(NO)
);

CREATE TABLE QNA_FILE (
    NO          NUMBER          PRIMARY KEY,
    OFILE       VARCHAR2(300)   NOT NULL,
    NFILE       VARCHAR2(300)   NOT NULL,
    REGDATE     DATE            DEFAULT SYSDATE,
    QNANO       NUMBER          REFERENCES QNA(NO)
);

CREATE TABLE CATALOG (
    NO          NUMBER          PRIMARY KEY,
    TITLE       VARCHAR2(200)   NOT NULL,
    CONTENT     CLOB,
    REGDATE     DATE            DEFAULT SYSDATE,
    VISITCOUNT  NUMBER          DEFAULT 0
);

CREATE TABLE CATALOG_FILE (
    NO          NUMBER          PRIMARY KEY,
    OFILE       VARCHAR2(300)   NOT NULL,
    NFILE       VARCHAR2(300)   NOT NULL,
    REGDATE     DATE            DEFAULT SYSDATE,
    CATALNO     NUMBER          REFERENCES CATALOG(NO)
);

CREATE TABLE NOTICE (
    NO          NUMBER          PRIMARY KEY,
    TITLE       VARCHAR2(200)   NOT NULL,
    CONTENT     CLOB,
    REGDATE     DATE            DEFAULT SYSDATE,
    VISITCOUNT  NUMBER          DEFAULT 0
);

CREATE TABLE NOTICE_FILE (
    NO          NUMBER          PRIMARY KEY,
    OFILE       VARCHAR2(300)   NOT NULL,
    NFILE       VARCHAR2(300)   NOT NULL,
    REGDATE     DATE            DEFAULT SYSDATE,
    NOTICENO    NUMBER          REFERENCES NOTICE(NO)
);

CREATE TABLE MAGAZINE (
    NO          NUMBER          PRIMARY KEY,
    TITLE       VARCHAR2(200)   NOT NULL,
    TEXT        VARCHAR2(500)   NOT NULL,
    POSTER      VARCHAR2(300)   NOT NULL,
    CONTENT     CLOB,
    REGDATE     DATE            DEFAULT SYSDATE,
    MTYPE       VARCHAR2(20)    NOT NULL
);

CREATE TABLE FAQ (
    NO          NUMBER          PRIMARY KEY,
    TITLE       VARCHAR2(200)   NOT NULL,
    CATE        VARCHAR2(100)   NOT NULL,
    CONTENT     CLOB,
    REGDATE     DATE            DEFAULT SYSDATE
);

-- 시퀀스 삭제
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_MAGAZINE;
DROP SEQUENCE SEQ_NOTICE_FILE;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_ITEM_REIVEW_FILE;
DROP SEQUENCE SEQ_ITEM_REIVEW;
DROP SEQUENCE SEQ_CATALOG_FILE;
DROP SEQUENCE SEQ_CATALOG;
DROP SEQUENCE SEQ_QNA_FILE;
DROP SEQUENCE SEQ_QNA;
DROP SEQUENCE SEQ_ITEM;
DROP SEQUENCE SEQ_ITEM_IMAGE;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_FAQ INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_MAGAZINE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_NOTICE_FILE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_NOTICE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_ITEM_REIVEW_FILE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_ITEM_REIVEW INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_CATALOG_FILE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_CATALOG INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_QNA_FILE INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_QNA INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_CART INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_ITEM INCREMENT BY 1 START WITH 1 MINVALUE 1;
CREATE SEQUENCE SEQ_ITEM_IMAGE INCREMENT BY 1 START WITH 1 MINVALUE 1;


